<?php

return array(
'NRouter'=>'nano.router.NRouter',
'NUserAgent'=>'nano.NUserAgent',
'NDatabase'=>'nano.db.NDatabase',
'NStorage'=>'nano.storage.NStorage',
'NFileStorageAdapter'=>'nano.storage.adapters.NFileStorageAdapter',
'NStorageAdapterBase'=>'nano.storage.NStorageAdapterBase',
'IStorageAdapter'=>'nano.storage.IStorageAdapter',
'NCookieStorageAdapter'=>'nano.storage.adapters.NCookieStorageAdapter',
'NSessionStorageAdapter'=>'nano.storage.adapters.NSessionStorageAdapter',
'NDependencyResolver'=>'nano.core.NDependencyResolver',
'NHtmlAssets'=>'nano.html.NHtmlAssets',
'NHtml'=>'nano.html.NHtml',
'NDraw'=>'nano.render.NDraw',
'NHtmlHeader'=>'nano.html.NHtmlHeader',
'NClip'=>'nano.render.NClip',
'NHtmlLayout'=>'nano.html.NHtmlLayout',
'NApplication'=>'nano.NApplication',
'NRouterAdapterBase'=>'nano.router.NRouterAdapterBase',
'IRouterAdapter'=>'nano.router.IRouterAdapter',
'NController'=>'nano.mvc.NController',
'NAction'=>'nano.mvc.action.NAction',
'NActionBase'=>'nano.mvc.action.NActionBase',
'NValidate'=>'nano.core.NValidate',
);